#!/usr/bin/env python

import sys
from py2neo import neo4j

graph_db = neo4j.GraphDatabaseService("http://localhost:7474/db/data/")

times = int(sys.argv[1])
count = int(sys.argv[2])
for t in range(times):
    props = [{"number": i} for i in range(count)]
    graph_db.create_nodes(*props)

