#!/usr/bin/env python

import sys
from py2neo import neo4j, cypher

graph_db = neo4j.GraphDatabaseService("http://localhost:7474/db/data/")

times = int(sys.argv[1])
count = int(sys.argv[2])
for t in range(times):
    props = ["n{0}={{number:{0}}}".format(i) for i in range(count)]
    query = "CREATE " + ",".join(props) + " RETURN n0;"
    try:
        cypher.execute(query, graph_db)
    except:
        #sys.stderr.write(repr(sys.exc_info()))
        sys.exit(1)

